### PR TITLE
tests: properly test `Isomorphic`

### LINKED ISSUE #6258: [BUG] Tests of `Isomorphic`
### Description

Note that the [_tests_](https://github.com/TheAlgorithms/Java/blob/b3c2c7a2319659d57898f35c5d5ede458c4a5925/src/test/java/com/thealgorithms/strings/IsomorphicTest.java) of [`Isomorphic`](https://github.com/TheAlgorithms/Java/blob/b3c2c7a2319659d57898f35c5d5ede458c4a5925/src/main/java/com/thealgorithms/strings/Isomorphic.java) are not executed.

### Steps to reproduce

1. run `mvn test`
2. the output contains:
```
(1) [WARNING] @Test method 'public static void com.thealgorithms.strings.IsomorphicTest.main(java.lang.String[])' must not be static. It will not be executed.
    Source: MethodSource [className = 'com.thealgorithms.strings.IsomorphicTest', methodName = 'main', methodParameterTypes = '[Ljava.lang.String;']
            at com.thealgorithms.strings.IsomorphicTest.main(SourceFile:0)
```

### Excepted behavior

Tests should be executed.

### Screenshots

_No response_

### Additional context

Update the existing test file. I suggest to express the tests as _parametrized_ (search for `@ParameterizedTest` to see examples, e.g. [`BandwidthAllocationTest`](https://github.com/TheAlgorithms/Java/blob/b3c2c7a2319659d57898f35c5d5ede458c4a5925/src/test/java/com/thealgorithms/greedyalgorithms/BandwidthAllocationTest.java)).

### PR DESCRIPTION
**Pull request by raveendra11**
Fixes #6258

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

### CODE REVIEW

File: src/test/java/com/thealgorithms/strings/IsomorphicTest.java [hunk 1]
```diff
@@ -1,31 +1,21 @@
...
+    public void testCheckStrings(String str1, String str2, Boolean expected) {
+        assertEquals(expected, Isomorphic.checkStrings(str1, str2));
+    }
 
-        assertTrue(Isomorphic.checkStrings(str1, str2));
-        assertTrue(Isomorphic.checkStrings(str3, str4));
-        assertFalse(Isomorphic.checkStrings(str5, str6));
-        assertFalse(Isomorphic.checkStrings(str7, str8));
+    private static Stream<Arguments> isomorphicProvider() {
+        return Stream.of(Arguments.of("abbbbaac", "kffffkkd", Boolean.TRUE), Arguments.of("xyxyxy", "bnbnbn", Boolean.TRUE), Arguments.of("ghjknnmm", "wertpopo", Boolean.FALSE), Arguments.of("aaammmnnn", "ggghhhbbj", Boolean.FALSE));
```
Comment (vil02) [inline src/test/java/com/thealgorithms/strings/IsomorphicTest.java:19]:
```suggestion
        return Stream.of(Arguments.of("", "", Boolean.TRUE), Arguments.of("", "a", Boolean.FALSE), Arguments.of("aaa", "aa", Boolean.FALSE), Arguments.of("abbbbaac", "kffffkkd", Boolean.TRUE), Arguments.of("xyxyxy", "bnbnbn", Boolean.TRUE), Arguments.of("ghjknnmm", "wertpopo", Boolean.FALSE),
            Arguments.of("aaammmnnn", "ggghhhbbj", Boolean.FALSE));
```

Using this opportunity, we can add the _missing_ test cases (cf. the coverage report):
- inputs with different length (not covered at all),
- _all time classics_ - some empty inputs

File: src/test/java/com/thealgorithms/strings/IsomorphicTest.java [hunk 2]
```diff
@@ -1,31 +1,21 @@
...
 
-        String str5 = "ghjknnmm";
-        String str6 = "wertpopo";
-
-        String str7 = "aaammmnnn";
-        String str8 = "ggghhhbbj";
+    @ParameterizedTest
+    @MethodSource("isomorphicProvider")
+    public void testCheckStrings(String str1, String str2, Boolean expected) {
+        assertEquals(expected, Isomorphic.checkStrings(str1, str2));
```
Comment (vil02) [inline src/test/java/com/thealgorithms/strings/IsomorphicTest.java:15]: What do you think about:
```suggestion
        assertEquals(expected, Isomorphic.checkStrings(str1, str2));
        assertEquals(expected, Isomorphic.checkStrings(str2, str1));
```

File: src/test/java/com/thealgorithms/strings/IsomorphicTest.java [hunk 3]
```diff
@@ -1,31 +1,21 @@
...
+    }
 
-        assertTrue(Isomorphic.checkStrings(str1, str2));
-        assertTrue(Isomorphic.checkStrings(str3, str4));
-        assertFalse(Isomorphic.checkStrings(str5, str6));
-        assertFalse(Isomorphic.checkStrings(str7, str8));
+    private static Stream<Arguments> isomorphicProvider() {
```
Comment (vil02) [inline src/test/java/com/thealgorithms/strings/IsomorphicTest.java:18]: `isomorphicProvider` sounds a bit artificial and this method does not provide only isomorphic strings. What do you think about another name like `inputs` or `testCases`?

**Review by vil02 — CHANGES_REQUESTED** [review]
Thanks for this PR. I made some minor comments, which could be resolved quickly. Afterwards this can be merged.

File: src/test/java/com/thealgorithms/strings/IsomorphicTest.java (hunk 3 above)
Comment (raveendra11) [reply src/test/java/com/thealgorithms/strings/IsomorphicTest.java:19]: shall i go with inputs?

Comment (vil02) [reply src/test/java/com/thealgorithms/strings/IsomorphicTest.java:19]: We can go with `inputs`.
